/**
 * Sample Government Schemes Data
 * Used as fallback when India.gov.in API is unavailable
 */

export const sampleSchemes = [
  {
    schemeId: 'pm-kisan-samman-nidhi',
    name: 'PM-KISAN (Pradhan Mantri Kisan Samman Nidhi)',
    description: 'Financial assistance of Rs. 6000 per year to all farmer families across the country in three equal installments of Rs. 2000 each, every four months.',
    category: ['Agriculture,Rural & Environment'],
    ministry: 'Ministry of Agriculture & Farmers Welfare',
    tags: ['Agriculture', 'Farmers', 'Financial Assistance', 'Rural'],
    state: null,
  },
  {
    schemeId: 'ayushman-bharat',
    name: 'Ayushman Bharat - Pradhan Mantri Jan Arogya Yojana (PM-JAY)',
    description: 'Health insurance scheme providing coverage of Rs. 5 lakhs per family per year for secondary and tertiary care hospitalization.',
    category: ['Health & Wellness'],
    ministry: 'Ministry of Health and Family Welfare',
    tags: ['Health', 'Insurance', 'Medical', 'BPL'],
    state: null,
  },
  {
    schemeId: 'pmay-gramin',
    name: 'Pradhan Mantri Awas Yojana - Gramin (PMAY-G)',
    description: 'Provides financial assistance for construction of pucca houses to all houseless and households living in kutcha and dilapidated houses in rural areas.',
    category: ['Social welfare & Empowerment'],
    ministry: 'Ministry of Rural Development',
    tags: ['Housing', 'Rural', 'BPL', 'Infrastructure'],
    state: null,
  },
  {
    schemeId: 'mid-day-meal',
    name: 'Mid-Day Meal Scheme',
    description: 'Provides free lunch to children in government and government-aided schools to improve nutritional levels and encourage school attendance.',
    category: ['Education & Learning'],
    ministry: 'Ministry of Education',
    tags: ['Education', 'Children', 'Nutrition', 'School'],
    state: null,
  },
  {
    schemeId: 'pmegp',
    name: 'Prime Minister Employment Generation Programme (PMEGP)',
    description: 'Credit-linked subsidy programme for generating self-employment opportunities through establishment of micro-enterprises in non-farm sector.',
    category: ['Business & Entrepreneurship'],
    ministry: 'Ministry of Micro, Small and Medium Enterprises',
    tags: ['Employment', 'Entrepreneurship', 'MSME', 'Loan'],
    state: null,
  },
  {
    schemeId: 'pmjdy',
    name: 'Pradhan Mantri Jan Dhan Yojana (PMJDY)',
    description: 'National Mission for Financial Inclusion to ensure access to financial services like banking, savings, deposit accounts, remittance, credit, insurance, pension.',
    category: ['Social welfare & Empowerment'],
    ministry: 'Ministry of Finance',
    tags: ['Banking', 'Financial Inclusion', 'Insurance', 'Pension'],
    state: null,
  },
  {
    schemeId: 'pmuy',
    name: 'Pradhan Mantri Ujjwala Yojana (PMUY)',
    description: 'Provides LPG connections to women from Below Poverty Line (BPL) households to safeguard their health and reduce indoor air pollution.',
    category: ['Social welfare & Empowerment'],
    ministry: 'Ministry of Petroleum & Natural Gas',
    tags: ['LPG', 'Women', 'BPL', 'Health'],
    state: null,
  },
  {
    schemeId: 'pmkvy',
    name: 'Pradhan Mantri Kaushal Vikas Yojana (PMKVY)',
    description: 'Skill development scheme providing training to youth in industry-relevant skills to enhance their employability.',
    category: ['Skills & Employment'],
    ministry: 'Ministry of Skill Development and Entrepreneurship',
    tags: ['Skill Development', 'Training', 'Youth', 'Employment'],
    state: null,
  },
  {
    schemeId: 'swachh-bharat-mission',
    name: 'Swachh Bharat Mission',
    description: 'Campaign to clean streets, roads and infrastructure of cities, towns and rural areas. Includes construction of toilets and promoting cleanliness.',
    category: ['Agriculture,Rural & Environment'],
    ministry: 'Ministry of Jal Shakti',
    tags: ['Sanitation', 'Cleanliness', 'Toilets', 'Rural'],
    state: null,
  },
  {
    schemeId: 'beti-bachao-beti-padhao',
    name: 'Beti Bachao Beti Padhao',
    description: 'Aims to generate awareness and improve the efficiency of welfare services for girls. Focuses on preventing gender-biased sex selection and ensuring survival, protection and education of girl child.',
    category: ['Social welfare & Empowerment'],
    ministry: 'Ministry of Women and Child Development',
    tags: ['Women', 'Girl Child', 'Education', 'Empowerment'],
    state: null,
  },
  {
    schemeId: 'national-scholarship-portal',
    name: 'National Scholarship Portal',
    description: 'One-stop solution for various scholarships provided by Government of India for students belonging to different categories.',
    category: ['Education & Learning'],
    ministry: 'Ministry of Education',
    tags: ['Scholarship', 'Students', 'Education', 'Financial Aid'],
    state: null,
  },
  {
    schemeId: 'atal-pension-yojana',
    name: 'Atal Pension Yojana (APY)',
    description: 'Pension scheme for all citizens, particularly targeting unorganized sector workers. Provides guaranteed minimum pension based on contribution.',
    category: ['Social welfare & Empowerment'],
    ministry: 'Ministry of Finance',
    tags: ['Pension', 'Social Security', 'Retirement', 'Workers'],
    state: null,
  },
  {
    schemeId: 'pmfby',
    name: 'Pradhan Mantri Fasal Bima Yojana (PMFBY)',
    description: 'Crop insurance scheme providing financial support to farmers suffering crop loss/damage arising out of unforeseen events.',
    category: ['Agriculture,Rural & Environment'],
    ministry: 'Ministry of Agriculture & Farmers Welfare',
    tags: ['Agriculture', 'Insurance', 'Farmers', 'Crop'],
    state: null,
  },
  {
    schemeId: 'stand-up-india',
    name: 'Stand-Up India Scheme',
    description: 'Facilitates bank loans between Rs. 10 lakh and Rs. 1 crore to at least one SC/ST borrower and one woman borrower per bank branch for setting up greenfield enterprise.',
    category: ['Business & Entrepreneurship'],
    ministry: 'Ministry of Finance',
    tags: ['Entrepreneurship', 'Women', 'SC/ST', 'Loan'],
    state: null,
  },
  {
    schemeId: 'pmgsy',
    name: 'Pradhan Mantri Gram Sadak Yojana (PMGSY)',
    description: 'Provides connectivity to unconnected habitations in rural areas through good all-weather roads.',
    category: ['Agriculture,Rural & Environment'],
    ministry: 'Ministry of Rural Development',
    tags: ['Infrastructure', 'Roads', 'Rural', 'Connectivity'],
    state: null,
  },
];
